### ISSUE TITLE
Weird spacing when button is toggled

### ISSUE THREAD

**Issue by catthehacker** [nektro/mantle#65]
![image](https://user-images.githubusercontent.com/31106839/76895077-38bcea80-6887-11ea-8e35-3fc887c23e87.png)
currently looks better with my fix:
```css
x-2s-toggle label input:checked + span::before {
    transform: translateX(2em);
}
```
